"""AI-powered test case generation using an LLM.

Reads a trace log and uses an LLM to generate pytest test cases with varied
inputs (edge cases, boundary values, error conditions). Expected values are
verified by calling the real traced function -- the LLM only proposes inputs,
it never provides expected outputs that go unverified.

Covers plain, top-level functions, including the entry script's own
top-level functions when its path is provided. An AI-proposed input that
raises during verification is rendered as a pytest.raises(...) test when
the raised exception class is referenceable (importable by a plain
module.Name path, or defined in the entry script itself); otherwise it's
skipped.

Configurable via env vars:
  OPENAI_API_KEY  -- API key (required for OpenAI)
  OPENAI_BASE_URL -- custom endpoint (OpenAI, Anthropic, OpenRouter, Ollama, etc.)
  AI_TRACER_MODEL -- model name (default: gpt-4o-mini)
"""

import ast
import builtins
import copy
import inspect
import json
import os
import sys
from pathlib import Path

from ai_tracer import generator

_GENERATED_MARKER = "# generated by ai-tracer - AI-generated test cases, do not edit"
_UNRESOLVED = object()


def _is_generated_file(path):
    try:
        with path.open(encoding="utf-8") as fh:
            return fh.readline().rstrip("\n") == _GENERATED_MARKER
    except (OSError, UnicodeDecodeError):
        return False


def _would_clobber(path):
    return path.exists() and not _is_generated_file(path)


def generate_ai_tests(
    trace_log_path,
    target_dir,
    output_dir="generated_tests",
    api_key=None,
    base_url=None,
    model=None,
    entry_script=None,
):
    """Generate AI-powered test cases from a trace log.

    Args:
        trace_log_path: Path to the trace log JSON file.
        target_dir: Directory containing the target source code.
        output_dir: Directory to write generated tests to.
        api_key: LLM API key (defaults to OPENAI_API_KEY env var).
        base_url: LLM API base URL (defaults to OPENAI_BASE_URL env var).
        model: LLM model name (defaults to AI_TRACER_MODEL env var or gpt-4o-mini).
        entry_script: Path to the entry script (for __main__ functions).

    Returns:
        List of paths to generated test files.
    """
    calls = json.loads(Path(trace_log_path).read_text())
    target_dir = str(Path(target_dir).resolve())
    if entry_script is not None:
        entry_script = str(Path(entry_script).resolve())
    output_path = Path(output_dir).resolve()

    calls_by_module = {}
    module_cache = {}
    signature_cache = {}

    original_sys_path = list(sys.path)
    original_sys_modules = dict(sys.modules)
    original_cwd = os.getcwd()
    sys.path.insert(0, target_dir)

    local_names = generator._local_module_names(target_dir)
    for name in list(sys.modules):
        if name.split(".")[0] in local_names:
            sys.modules.pop(name, None)

    try:
        # "__main__" calls are set aside and classified last: resolving them
        # loads the entry script, which runs its top-level code and could
        # mutate a sibling module before it's ever verified here.
        main_calls = []
        for call in calls:
            if call["module"] == "__main__":
                main_calls.append(call)
                continue
            reason = generator._skip_reason(call, module_cache, signature_cache)
            if reason is None:
                calls_by_module.setdefault(call["module"], []).append(call)
            else:
                print(
                    f"Skipping AI test for {call['module']}.{call['qualname']}: {reason}",
                    file=sys.stderr,
                )

        # Generate AI tests while modules are still in sys.modules --
        # _call_real_function calls the real traced function, which may
        # depend on sibling modules that were just imported.
        output_path.mkdir(exist_ok=True, parents=True)

        # generate() already writes this conftest.py, but generate_ai_tests()
        # is also independently callable without going through generate()
        # first -- written here too so that path gets the same eviction setup.
        conftest_path = output_path / "conftest.py"
        if not generator._would_clobber(conftest_path):
            conftest_path.write_text(generator._render_conftest(target_dir))

        # Clear previously generated AI tests first, so a module that's no
        # longer in the trace doesn't leave a stale test_*_ai.py behind.
        # Only files carrying our marker are removed.
        for existing in output_path.glob("test_*.py"):
            if _is_generated_file(existing):
                existing.unlink()

        used_names = {}
        written_paths = []

        def _write_module_tests(module_name, module_calls):
            test_cases_by_function = _generate_for_module(
                module_name,
                module_calls,
                module_cache,
                signature_cache,
                target_dir,
                api_key,
                base_url,
                model,
            )
            if not test_cases_by_function:
                return

            test_code = _render_test_module(
                module_name, test_cases_by_function, target_dir, entry_script
            )
            base = f"test_{module_name.replace('.', '_')}_ai"
            file_name = f"{base}.py"
            suffix = 1
            while file_name in used_names or _would_clobber(output_path / file_name):
                file_name = f"{base}_{suffix}.py"
                suffix += 1
            used_names[file_name] = module_name
            test_path = output_path / file_name
            test_path.write_text(test_code)
            written_paths.append(test_path)

        for module_name in sorted(calls_by_module):
            _write_module_tests(module_name, calls_by_module[module_name])

        # Only loaded now, and only if there's actually a "__main__" call to
        # resolve -- see the comment above the first pass for why loading it
        # any earlier would risk corrupting a sibling module's verification.
        if main_calls:
            if entry_script is not None:
                module_cache["__main__"] = generator._load_entry_module(entry_script)
            entry_module_calls = []
            for call in main_calls:
                reason = generator._skip_reason(call, module_cache, signature_cache)
                if reason is None:
                    entry_module_calls.append(call)
                else:
                    print(
                        f"Skipping AI test for {call['module']}.{call['qualname']}: {reason}",
                        file=sys.stderr,
                    )
            if entry_module_calls:
                _write_module_tests("__main__", entry_module_calls)
    finally:
        sys.path[:] = original_sys_path
        sys.modules.clear()
        sys.modules.update(original_sys_modules)
        os.chdir(original_cwd)

    return written_paths


def _generate_for_module(
    module_name,
    module_calls,
    module_cache,
    signature_cache,
    target_dir,
    api_key,
    base_url,
    model,
):
    # Group calls by qualname, preserving first-appearance order.
    functions = {}
    for call in module_calls:
        qualname = call["qualname"]
        if qualname not in functions:
            functions[qualname] = []
        functions[qualname].append(call)

    test_cases_by_function = {}
    for qualname, recorded_calls in functions.items():
        signature = generator._get_signature(
            module_calls[0]["module"], qualname, module_cache, signature_cache
        )
        if signature is None:
            print(
                f"Skipping AI test for {module_name}.{qualname}: "
                "function no longer exists or can't be introspected",
                file=sys.stderr,
            )
            continue

        prompt = _build_prompt(qualname, signature, recorded_calls)
        try:
            response = _call_llm(
                prompt,
                target_dir=target_dir,
                api_key=api_key,
                base_url=base_url,
                model=model,
            )
        except ImportError:
            raise
        except Exception as exc:  # noqa: BLE001 - LLM call is an external API, any failure just means skip
            print(
                f"Skipping AI tests for {module_name}.{qualname}: LLM call failed: {exc}",
                file=sys.stderr,
            )
            continue
        proposed_inputs = _parse_response(response, qualname)

        verified_tests = []
        for args in proposed_inputs:
            if not all(_is_renderable(value) for value in args.values()):
                # e.g. the LLM proposed x=1e309, which ast.literal_eval parses
                # as float('inf') -- a real value, but its repr ('inf') isn't
                # a literal the generated test could embed as an argument.
                print(
                    f"Skipping AI test for {module_name}.{qualname}({args}): "
                    "a proposed argument can't be rendered as a literal",
                    file=sys.stderr,
                )
                continue
            result, exc_type = _call_real_function(
                module_calls[0]["module"], qualname, args, module_cache
            )
            if result is _UNRESOLVED:
                print(
                    f"Skipping AI test for {module_name}.{qualname}({args}): "
                    "function could not be resolved for verification",
                    file=sys.stderr,
                )
                continue
            if exc_type is not None:
                if not _is_referenceable_exception(exc_type, module_cache):
                    print(
                        f"Skipping AI test for {module_name}.{qualname}({args}): "
                        f"raised exception {exc_type.__qualname__} can't be "
                        "referenced in a pytest.raises(...)",
                        file=sys.stderr,
                    )
                    continue
                verified_tests.append((args, None, exc_type))
                continue
            if not _is_renderable(result):
                print(
                    f"Skipping AI test for {module_name}.{qualname}({args}): "
                    "verified return value can't be rendered as a test assertion",
                    file=sys.stderr,
                )
                continue
            # A deep copy: if `result` is a mutable object the target keeps
            # a reference to, a later verification call could mutate it in
            # place before this test case is rendered, changing the value.
            verified_tests.append((args, copy.deepcopy(result), None))

        if verified_tests:
            test_cases_by_function[qualname] = verified_tests

    return test_cases_by_function


def _sanitized_signature(signature):
    # Only parameter names, no defaults/annotations -- a default like
    # token="secret123" would otherwise leak source-derived values to the
    # LLM, same as sending source code would.
    return "(" + ", ".join(signature.parameters) + ")"


def _equals_default(value, default):
    try:
        return value == default
    except Exception:  # noqa: BLE001 - a weird default's __eq__ must never crash generation
        return False


def _redact_default_valued_args(args, signature):
    # The trace can't tell an omitted argument from one passed explicitly
    # (see README's "default arguments" limitation), so an omitted arg's
    # recorded value is a source default -- redact it before it reaches the prompt.
    redacted = {}
    for name, value in args.items():
        param = signature.parameters.get(name)
        has_default = param is not None and param.default is not inspect.Parameter.empty
        is_default_value = has_default and _equals_default(value, param.default)
        redacted[name] = "<default>" if is_default_value else value
    return redacted


def _contains_default(value, default):
    # Beyond an exact match, a default can be embedded in a larger derived
    # value (`'Bearer ' + token`) or nested in a container (`{'token': token}`),
    # so both are checked recursively, not just direct equality.
    if _equals_default(value, default):
        return True
    if isinstance(default, str) and isinstance(value, str) and default:
        return default in value
    if isinstance(value, (list, tuple)):
        return any(_contains_default(item, default) for item in value)
    if isinstance(value, dict):
        return any(
            _contains_default(key, default) or _contains_default(val, default)
            for key, val in value.items()
        )
    return False


def _leaf_default_values(default):
    # Recursively yields every leaf scalar inside a default value -- a
    # container default can have just one piece extracted and returned,
    # which a check against the whole container as one unit would miss.
    if isinstance(default, dict):
        for key, value in default.items():
            yield from _leaf_default_values(key)
            yield from _leaf_default_values(value)
    elif isinstance(default, (list, tuple)):
        for item in default:
            yield from _leaf_default_values(item)
    else:
        yield default


def _redact_default_valued_return(return_value, signature):
    # A function that echoes an omitted argument back out, directly or as
    # part of a larger value, would otherwise re-leak the same source
    # default through its recorded return value even though the arg is redacted above.
    for param in signature.parameters.values():
        if param.default is inspect.Parameter.empty:
            continue
        candidates = (param.default, *_leaf_default_values(param.default))
        if any(_contains_default(return_value, candidate) for candidate in candidates):
            return "<default>"
    return return_value


def _build_prompt(qualname, signature, recorded_calls):
    lines = [
        (
            "You are a Python testing expert. Generate test case inputs for "
            "the following function."
        ),
        (
            "Focus on edge cases, boundary values, and error conditions -- "
            "not just replaying recorded calls."
        ),
        "",
        f"Function: {qualname}",
        f"Signature: {qualname}{_sanitized_signature(signature)}",
        "",
        "Recorded calls (for reference):",
    ]
    for call in recorded_calls:
        args = _redact_default_valued_args(call["args"], signature)
        args_str = ", ".join(f"{name}={value!r}" for name, value in args.items())
        if call["raised"]:
            lines.append(f"- {qualname}({args_str}) raised {call['exception_type']}")
        else:
            return_value = _redact_default_valued_return(
                call["return_value"], signature
            )
            lines.append(f"- {qualname}({args_str}) returned {return_value!r}")
    lines.append("")
    lines.append(
        "Return test case inputs, one per line. Each line should be a function "
        "call with keyword arguments."
    )
    lines.append(
        f"Do NOT include assertions. Format: {qualname}(arg1=value1, arg2=value2)"
    )
    return "\n".join(lines)


_openai_client_cls = None


def _import_openai_client_cls(target_dir):
    # Cached: the import only needs to happen (and be shadow-guarded) once.
    # target_dir can be on sys.path more than once by now, so every occurrence
    # is set aside for this import -- else a target package named "openai" wins.
    global _openai_client_cls
    if _openai_client_cls is not None:
        return _openai_client_cls

    original_sys_path = list(sys.path)
    sys.path = [entry for entry in sys.path if entry != target_dir]
    try:
        from openai import OpenAI
    except ImportError:
        raise ImportError(
            "The 'openai' package is required for AI test generation. "
            "Install it with: pip install 'ai-tracer[ai]'"
        )
    finally:
        sys.path[:] = original_sys_path

    _openai_client_cls = OpenAI
    return _openai_client_cls


def _call_llm(prompt, target_dir=None, api_key=None, base_url=None, model=None):
    api_key = api_key or os.environ.get("OPENAI_API_KEY")
    base_url = base_url or os.environ.get("OPENAI_BASE_URL")
    model = model or os.environ.get("AI_TRACER_MODEL", "gpt-4o-mini")

    OpenAI = _import_openai_client_cls(target_dir)
    client = OpenAI(api_key=api_key, base_url=base_url)
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": "You are a Python testing expert."},
            {"role": "user", "content": prompt},
        ],
    )
    return response.choices[0].message.content


def _parse_response(response_text, qualname):
    # Extract function calls from the LLM response. Each line should be a
    # call like `qualname(arg1=value1, arg2=value2)`. Lines that don't parse
    # as a valid call to qualname are silently skipped.
    test_cases = []
    for line in response_text.strip().split("\n"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            tree = ast.parse(line, mode="eval")
        except SyntaxError:
            continue
        if not isinstance(tree.body, ast.Call):
            continue
        func = tree.body.func
        if not isinstance(func, ast.Name) or func.id != qualname:
            continue
        if tree.body.args:
            # Positional args aren't supported (the prompt asks for
            # keyword-only calls); don't silently drop them.
            continue
        args = {}
        ok = True
        for keyword in tree.body.keywords:
            if keyword.arg is None:
                ok = False
                break
            try:
                args[keyword.arg] = ast.literal_eval(keyword.value)
            except (ValueError, SyntaxError):
                ok = False
                break
        if ok:
            test_cases.append(args)
    return test_cases


# Types whose repr() ai-tracer trusts to be a faithful, re-runnable literal.
# Checked by exact type, not isinstance: a subclass overriding __eq__ can
# still repr like its builtin base but no longer behave like one for `==`.
_RENDERABLE_TYPES = (type(None), bool, int, float, str, bytes)
_RENDERABLE_CONTAINER_TYPES = (list, tuple, dict)


def _is_renderable(value):
    if type(value) in _RENDERABLE_TYPES:
        # Still rejects float('nan')/float('inf'): valid objects of a
        # renderable type, but their repr ('nan'/'inf') is a bare name,
        # not a literal, so it wouldn't parse back at all.
        try:
            ast.literal_eval(repr(value))
        except (ValueError, SyntaxError):
            return False
        return True
    if type(value) not in _RENDERABLE_CONTAINER_TYPES:
        return False
    if isinstance(value, dict):
        return all(
            _is_renderable(key) and _is_renderable(val) for key, val in value.items()
        )
    return all(_is_renderable(item) for item in value)


def _is_referenceable_exception(exc_type, module_cache):
    # False for a local/nested exception class: its __qualname__ contains a
    # dot, so it isn't reachable as a plain `module.Name` pytest.raises() needs.
    if "." in exc_type.__qualname__:
        return False
    # The generated file embeds this as literal `import x.y as ...` source
    # text, not just an importlib lookup -- an invalid identifier here would
    # be syntactically invalid there even if importlib itself could resolve it.
    if not generator._is_valid_import_name(exc_type.__name__):
        return False
    if exc_type.__module__ == "builtins":
        return getattr(builtins, exc_type.__name__, None) is exc_type
    if exc_type.__module__ in ("__main__", generator._ENTRY_MODULE_IMPORT_NAME):
        # A class defined while the entry script executed has that synthetic
        # load name as __module__, not "__main__" -- either way it's resolved
        # through the same cached entry module object, checked by identity below.
        module = module_cache.get("__main__")
        return (
            module is not None and getattr(module, exc_type.__name__, None) is exc_type
        )
    if not all(
        generator._is_valid_import_name(part) for part in exc_type.__module__.split(".")
    ):
        return False
    module = generator._get_module(exc_type.__module__, module_cache)
    return module is not None and getattr(module, exc_type.__name__, None) is exc_type


def _call_real_function(module_name, qualname, args, module_cache):
    # Call the real traced function with the AI-proposed arguments. The
    # return value or raised exception's type becomes the expected outcome --
    # never the LLM's claim about what the output should be.
    module = generator._get_module(module_name, module_cache)
    if module is None:
        return _UNRESOLVED, None
    try:
        function = getattr(module, qualname)
    except AttributeError:
        return _UNRESOLVED, None
    try:
        # A deep copy, not the caller's own dict: if the target mutates a
        # mutable argument in place, the version later rendered into the
        # test must still reflect the originally proposed input.
        return function(**copy.deepcopy(args)), None
    except KeyboardInterrupt:
        raise
    except BaseException as exc:  # noqa: BLE001 - not just Exception: a target
        # calling sys.exit() (SystemExit) is a valid outcome to verify too.
        return None, type(exc)


def _render_test_module(
    module_name, test_cases_by_function, target_dir, entry_script=None
):
    function_names = sorted(test_cases_by_function.keys())
    all_tests = [
        (args, result, exc_type)
        for tests in test_cases_by_function.values()
        for args, result, exc_type in tests
    ]

    has_raises = any(exc_type is not None for _, _, exc_type in all_tests)
    has_builtin_raises = any(
        exc_type is not None and exc_type.__module__ == "builtins"
        for _, _, exc_type in all_tests
    )
    is_entry_script = module_name == "__main__"
    # A class defined while the entry script executed has its synthetic load
    # name as __module__, not "__main__" -- but it's reachable through the
    # same cached entry module object, so it's referenced the same way.
    entry_exception_modules = ("__main__", generator._ENTRY_MODULE_IMPORT_NAME)
    needs_entry_module = is_entry_script or any(
        exc_type is not None and exc_type.__module__ in entry_exception_modules
        for _, _, exc_type in all_tests
    )
    exception_modules = sorted(
        {
            exc_type.__module__
            for _, _, exc_type in all_tests
            if exc_type is not None
            and exc_type.__module__ not in (("builtins",) + entry_exception_modules)
        }
    )

    # A traced function may be named the same as a helper import below
    # (e.g. `pytest`, `result`) -- traced names are reserved first so a
    # collision falls back to an alias instead of silently shadowing it.
    reserved = set(function_names)

    def _reserve(base):
        alias = base
        while alias in reserved:
            alias = "_" + alias
        reserved.add(alias)
        return alias

    pytest_alias = _reserve("pytest") if has_raises else None
    builtins_alias = _reserve("_raises_builtins") if has_builtin_raises else None
    entry_util_alias = _reserve("_importlib_util") if needs_entry_module else None
    entry_spec_var = _reserve("_entry_spec") if needs_entry_module else None
    entry_module_var = _reserve("_entry_module") if needs_entry_module else None
    exception_aliases = {
        module: _reserve("_raises_" + module.replace(".", "_"))
        for module in exception_modules
    }
    result_var = _reserve("result")

    lines = [_GENERATED_MARKER, "import sys"]
    if has_raises:
        lines.append(
            "import pytest"
            if pytest_alias == "pytest"
            else f"import pytest as {pytest_alias}"
        )
    if has_builtin_raises:
        lines.append(f"import builtins as {builtins_alias}")
    if needs_entry_module:
        lines.append(f"import importlib.util as {entry_util_alias}")
    lines += ["", f"sys.path.insert(0, {target_dir!r})"]

    if needs_entry_module:
        # Loaded under a synthetic name, not "__main__", so the entry
        # script's own `if __name__ == "__main__":` guard doesn't re-run.
        lines.append(
            f"{entry_spec_var} = {entry_util_alias}.spec_from_file_location("
            f"{generator._ENTRY_MODULE_IMPORT_NAME!r}, {entry_script!r})"
        )
        lines.append(
            f"{entry_module_var} = {entry_util_alias}.module_from_spec({entry_spec_var})"
        )
        lines.append(f"{entry_spec_var}.loader.exec_module({entry_module_var})")
        # Patched back to "__main__" after exec so a function reading
        # __name__ at call time sees what it saw when traced.
        lines.append(f'{entry_module_var}.__name__ = "__main__"')

    if is_entry_script:
        for name in function_names:
            lines.append(f"{name} = {entry_module_var}.{name}")
    else:
        lines.append(f"from {module_name} import {', '.join(function_names)}")
    for module in exception_modules:
        lines.append(f"import {module} as {exception_aliases[module]}")

    # Rendered in first-appearance trace order, not alphabetically -- for
    # shared mutable state, a test verified against a call made in that order
    # would no longer match the value it asserts on if run out of order.
    for qualname in test_cases_by_function:
        tests = test_cases_by_function[qualname]
        for i, (args, result, exc_type) in enumerate(tests):
            args_str = ", ".join(f"{name}={value!r}" for name, value in args.items())
            lines += ["", ""]
            lines.append(f"def test_{qualname}_{i}():")
            if exc_type is not None:
                if exc_type.__module__ == "builtins":
                    exc_ref = f"{builtins_alias}.{exc_type.__name__}"
                elif exc_type.__module__ in entry_exception_modules:
                    exc_ref = f"{entry_module_var}.{exc_type.__name__}"
                else:
                    exc_ref = (
                        f"{exception_aliases[exc_type.__module__]}.{exc_type.__name__}"
                    )
                lines.append(f"    with {pytest_alias}.raises({exc_ref}):")
                lines.append(f"        {qualname}({args_str})")
            else:
                lines.append(f"    {result_var} = {qualname}({args_str})")
                lines.append(f"    assert {result_var} == {result!r}")

    return "\n".join(lines) + "\n"


def main():
    argv = sys.argv[1:]
    if len(argv) not in (2, 3, 4):
        print(
            "usage: python -m ai_tracer.ai_generator <trace_log> <target_dir> "
            "[output_dir] [entry_script]",
            file=sys.stderr,
        )
        sys.exit(1)
    trace_log_path, target_dir, *rest = argv
    output_dir = rest[0] if len(rest) > 0 else "generated_tests"
    entry_script = rest[1] if len(rest) > 1 else None
    for path in generate_ai_tests(
        trace_log_path, target_dir, output_dir, entry_script=entry_script
    ):
        print(path)


if __name__ == "__main__":
    main()
