"""AI-powered test case generation using an LLM.

Reads a trace log and uses an LLM to generate pytest test cases with varied
inputs (edge cases, boundary values, error conditions). Expected values are
verified by calling the real traced function -- the LLM only proposes inputs,
it never provides expected outputs that go unverified.

Only plain functions whose AI-proposed inputs return a value are covered so
far -- an input that raises during verification is skipped, not rendered as
a test.

Configurable via env vars:
  OPENAI_API_KEY  -- API key (required for OpenAI)
  OPENAI_BASE_URL -- custom endpoint (OpenAI, Anthropic, OpenRouter, Ollama, etc.)
  AI_TRACER_MODEL -- model name (default: gpt-4o-mini)
"""

import ast
import copy
import inspect
import json
import os
import sys
from pathlib import Path

from ai_tracer import generator

_GENERATED_MARKER = "# generated by ai-tracer - AI-generated test cases, do not edit"
_UNRESOLVED = object()
_RAISED = object()


def _is_generated_file(path):
    try:
        with path.open(encoding="utf-8") as fh:
            return fh.readline().rstrip("\n") == _GENERATED_MARKER
    except (OSError, UnicodeDecodeError):
        return False


def _would_clobber(path):
    return path.exists() and not _is_generated_file(path)


def generate_ai_tests(
    trace_log_path,
    target_dir,
    output_dir="generated_tests",
    api_key=None,
    base_url=None,
    model=None,
):
    """Generate AI-powered test cases from a trace log.

    Args:
        trace_log_path: Path to the trace log JSON file.
        target_dir: Directory containing the target source code.
        output_dir: Directory to write generated tests to.
        api_key: LLM API key (defaults to OPENAI_API_KEY env var).
        base_url: LLM API base URL (defaults to OPENAI_BASE_URL env var).
        model: LLM model name (defaults to AI_TRACER_MODEL env var or gpt-4o-mini).

    Returns:
        List of paths to generated test files.
    """
    calls = json.loads(Path(trace_log_path).read_text())
    target_dir = str(Path(target_dir).resolve())
    output_path = Path(output_dir).resolve()

    calls_by_module = {}
    module_cache = {}
    signature_cache = {}

    original_sys_path = list(sys.path)
    original_sys_modules = dict(sys.modules)
    original_cwd = os.getcwd()
    sys.path.insert(0, target_dir)

    local_names = generator._local_module_names(target_dir)
    for name in list(sys.modules):
        if name.split(".")[0] in local_names:
            sys.modules.pop(name, None)

    try:
        # No entry_script is ever passed to generator._skip_reason, so an
        # entry-script ("__main__") function is skipped the same way it
        # already is when generate() itself isn't given one -- not
        # supported by AI generation yet.
        for call in calls:
            reason = generator._skip_reason(call, module_cache, signature_cache)
            if reason is None:
                calls_by_module.setdefault(call["module"], []).append(call)
            else:
                print(
                    f"Skipping AI test for {call['module']}.{call['qualname']}: {reason}",
                    file=sys.stderr,
                )

        # Generate AI tests while modules are still in sys.modules --
        # _call_real_function calls the real traced function, which may
        # depend on sibling modules that were just imported.
        output_path.mkdir(exist_ok=True, parents=True)

        # generator.generate(ai=True) already writes this conftest.py as
        # part of its own deterministic-generation step, but generate_ai_tests()
        # is also independently callable (its own CLI, or directly) without
        # going through generate() first -- written here too so that path
        # gets the same one-time sys.path/eviction setup its own generated
        # tests rely on, instead of a bare sys.path.insert with no eviction.
        conftest_path = output_path / "conftest.py"
        if not generator._would_clobber(conftest_path):
            conftest_path.write_text(generator._render_conftest(target_dir))

        # Clear previously generated AI tests first, so a module that's no
        # longer in the trace doesn't leave a stale test_*_ai.py behind.
        # Only files carrying our marker are removed.
        for existing in output_path.glob("test_*.py"):
            if _is_generated_file(existing):
                existing.unlink()

        used_names = {}
        written_paths = []
        for module_name in sorted(calls_by_module):
            module_calls = calls_by_module[module_name]
            test_cases_by_function = _generate_for_module(
                module_name,
                module_calls,
                module_cache,
                signature_cache,
                target_dir,
                api_key,
                base_url,
                model,
            )
            if not test_cases_by_function:
                continue

            test_code = _render_test_module(
                module_name, test_cases_by_function, target_dir
            )
            base = f"test_{module_name.replace('.', '_')}_ai"
            file_name = f"{base}.py"
            suffix = 1
            while file_name in used_names or _would_clobber(output_path / file_name):
                file_name = f"{base}_{suffix}.py"
                suffix += 1
            used_names[file_name] = module_name
            test_path = output_path / file_name
            test_path.write_text(test_code)
            written_paths.append(test_path)
    finally:
        sys.path[:] = original_sys_path
        sys.modules.clear()
        sys.modules.update(original_sys_modules)
        os.chdir(original_cwd)

    return written_paths


def _generate_for_module(
    module_name,
    module_calls,
    module_cache,
    signature_cache,
    target_dir,
    api_key,
    base_url,
    model,
):
    # Group calls by qualname, preserving first-appearance order.
    functions = {}
    for call in module_calls:
        qualname = call["qualname"]
        if qualname not in functions:
            functions[qualname] = []
        functions[qualname].append(call)

    test_cases_by_function = {}
    for qualname, recorded_calls in functions.items():
        signature = generator._get_signature(
            module_calls[0]["module"], qualname, module_cache, signature_cache
        )
        if signature is None:
            print(
                f"Skipping AI test for {module_name}.{qualname}: "
                "function no longer exists or can't be introspected",
                file=sys.stderr,
            )
            continue

        prompt = _build_prompt(qualname, signature, recorded_calls)
        try:
            response = _call_llm(
                prompt,
                target_dir=target_dir,
                api_key=api_key,
                base_url=base_url,
                model=model,
            )
        except ImportError:
            raise
        except Exception as exc:  # noqa: BLE001 - LLM call is an external API, any failure just means skip
            print(
                f"Skipping AI tests for {module_name}.{qualname}: LLM call failed: {exc}",
                file=sys.stderr,
            )
            continue
        proposed_inputs = _parse_response(response, qualname)

        verified_tests = []
        for args in proposed_inputs:
            if not all(_is_renderable(value) for value in args.values()):
                # e.g. the LLM proposed x=1e309, which ast.literal_eval
                # happily parses as float('inf') -- a real Python value,
                # but its repr ('inf') isn't a literal the generated test
                # could embed as an argument.
                print(
                    f"Skipping AI test for {module_name}.{qualname}({args}): "
                    "a proposed argument can't be rendered as a literal",
                    file=sys.stderr,
                )
                continue
            result = _call_real_function(
                module_calls[0]["module"], qualname, args, module_cache
            )
            if result is _UNRESOLVED:
                print(
                    f"Skipping AI test for {module_name}.{qualname}({args}): "
                    "function could not be resolved for verification",
                    file=sys.stderr,
                )
                continue
            if result is _RAISED:
                print(
                    f"Skipping AI test for {module_name}.{qualname}({args}): "
                    "raised during verification; AI-generated tests for "
                    "exceptions aren't supported yet",
                    file=sys.stderr,
                )
                continue
            if not _is_renderable(result):
                print(
                    f"Skipping AI test for {module_name}.{qualname}({args}): "
                    "verified return value can't be rendered as a test assertion",
                    file=sys.stderr,
                )
                continue
            # A deep copy: if `result` is a mutable object the target keeps
            # a reference to (e.g. a module-level list it returns), a later
            # verification call could mutate it in place before this test
            # case is ever rendered, silently changing the value already
            # accepted here for an earlier call.
            verified_tests.append((args, copy.deepcopy(result)))

        if verified_tests:
            test_cases_by_function[qualname] = verified_tests

    return test_cases_by_function


def _sanitized_signature(signature):
    # Only parameter names, no defaults/annotations -- a default like
    # token="secret123" would otherwise leak source-derived values to the
    # LLM, same as sending source code would.
    return "(" + ", ".join(signature.parameters) + ")"


def _equals_default(value, default):
    try:
        return value == default
    except Exception:  # noqa: BLE001 - a weird default's __eq__ must never crash generation
        return False


def _redact_default_valued_args(args, signature):
    # The trace records every parameter present in the call frame, including
    # ones the caller left at their default (it can't tell the two apart --
    # see the README's "default arguments" limitation), so an omitted
    # argument's recorded value is the same source-embedded default the
    # signature line already strips. Redact anything that matches a
    # parameter's default before it ever reaches the "recorded calls"
    # section of the prompt.
    redacted = {}
    for name, value in args.items():
        param = signature.parameters.get(name)
        has_default = param is not None and param.default is not inspect.Parameter.empty
        is_default_value = has_default and _equals_default(value, param.default)
        redacted[name] = "<default>" if is_default_value else value
    return redacted


def _contains_default(value, default):
    # Beyond an exact match (`return token`), a default can be embedded in
    # a larger value the function derives -- `'Bearer ' + token` (substring)
    # or `{'token': token}` (nested in a container) -- so both are checked
    # recursively, not just direct equality.
    if _equals_default(value, default):
        return True
    if isinstance(default, str) and isinstance(value, str) and default:
        return default in value
    if isinstance(value, (list, tuple)):
        return any(_contains_default(item, default) for item in value)
    if isinstance(value, dict):
        return any(
            _contains_default(key, default) or _contains_default(val, default)
            for key, val in value.items()
        )
    return False


def _leaf_default_values(default):
    # Recursively yields every leaf scalar reachable inside a default value
    # -- a container default (e.g. cfg={'token': 'secret'}) can have just
    # one piece of it extracted and returned (`return cfg['token']`), which
    # a check against the whole container as one unit would miss.
    if isinstance(default, dict):
        for key, value in default.items():
            yield from _leaf_default_values(key)
            yield from _leaf_default_values(value)
    elif isinstance(default, (list, tuple)):
        for item in default:
            yield from _leaf_default_values(item)
    else:
        yield default


def _redact_default_valued_return(return_value, signature):
    # A function that echoes an omitted argument back out, directly or as
    # part of a larger value (e.g. `def connect(token="secret"): return
    # token` or `return "Bearer " + token`), would otherwise re-leak the
    # exact same source-embedded default through its recorded return value,
    # even though the argument itself is already redacted above.
    for param in signature.parameters.values():
        if param.default is inspect.Parameter.empty:
            continue
        candidates = (param.default, *_leaf_default_values(param.default))
        if any(_contains_default(return_value, candidate) for candidate in candidates):
            return "<default>"
    return return_value


def _build_prompt(qualname, signature, recorded_calls):
    lines = [
        (
            "You are a Python testing expert. Generate test case inputs for "
            "the following function."
        ),
        (
            "Focus on edge cases, boundary values, and error conditions -- "
            "not just replaying recorded calls."
        ),
        "",
        f"Function: {qualname}",
        f"Signature: {qualname}{_sanitized_signature(signature)}",
        "",
        "Recorded calls (for reference):",
    ]
    for call in recorded_calls:
        args = _redact_default_valued_args(call["args"], signature)
        args_str = ", ".join(f"{name}={value!r}" for name, value in args.items())
        if call["raised"]:
            lines.append(f"- {qualname}({args_str}) raised {call['exception_type']}")
        else:
            return_value = _redact_default_valued_return(
                call["return_value"], signature
            )
            lines.append(f"- {qualname}({args_str}) returned {return_value!r}")
    lines.append("")
    lines.append(
        "Return test case inputs, one per line. Each line should be a function "
        "call with keyword arguments."
    )
    lines.append(
        f"Do NOT include assertions. Format: {qualname}(arg1=value1, arg2=value2)"
    )
    return "\n".join(lines)


_openai_client_cls = None


def _import_openai_client_cls(target_dir):
    # Cached: the import only needs to happen (and be shadow-guarded) once.
    # target_dir can be on sys.path more than once by the time this runs --
    # generate_ai_tests() inserts it, and the CLI's own run() already left
    # an earlier copy there too (it doesn't restore sys.path for the target
    # process's own atexit handlers) -- so every occurrence of it, not just
    # sys.path[0], is set aside for this one import. Otherwise a target
    # file/package literally named "openai" could resolve here instead of
    # the real installed SDK.
    global _openai_client_cls
    if _openai_client_cls is not None:
        return _openai_client_cls

    original_sys_path = list(sys.path)
    sys.path = [entry for entry in sys.path if entry != target_dir]
    try:
        from openai import OpenAI
    except ImportError:
        raise ImportError(
            "The 'openai' package is required for AI test generation. "
            "Install it with: pip install 'ai-tracer[ai]'"
        )
    finally:
        sys.path[:] = original_sys_path

    _openai_client_cls = OpenAI
    return _openai_client_cls


def _call_llm(prompt, target_dir=None, api_key=None, base_url=None, model=None):
    api_key = api_key or os.environ.get("OPENAI_API_KEY")
    base_url = base_url or os.environ.get("OPENAI_BASE_URL")
    model = model or os.environ.get("AI_TRACER_MODEL", "gpt-4o-mini")

    OpenAI = _import_openai_client_cls(target_dir)
    client = OpenAI(api_key=api_key, base_url=base_url)
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": "You are a Python testing expert."},
            {"role": "user", "content": prompt},
        ],
    )
    return response.choices[0].message.content


def _parse_response(response_text, qualname):
    # Extract function calls from the LLM response. Each line should be a
    # call like `qualname(arg1=value1, arg2=value2)`. Lines that don't parse
    # as a valid call to qualname are silently skipped.
    test_cases = []
    for line in response_text.strip().split("\n"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            tree = ast.parse(line, mode="eval")
        except SyntaxError:
            continue
        if not isinstance(tree.body, ast.Call):
            continue
        func = tree.body.func
        if not isinstance(func, ast.Name) or func.id != qualname:
            continue
        if tree.body.args:
            # Positional args aren't supported (the prompt asks for
            # keyword-only calls); don't silently drop them.
            continue
        args = {}
        ok = True
        for keyword in tree.body.keywords:
            if keyword.arg is None:
                ok = False
                break
            try:
                args[keyword.arg] = ast.literal_eval(keyword.value)
            except (ValueError, SyntaxError):
                ok = False
                break
        if ok:
            test_cases.append(args)
    return test_cases


# Types whose repr() ai-tracer trusts to be a faithful, re-runnable literal.
# Anything else (a custom object, even one whose __repr__ happens to look
# like a literal) is rejected -- the rendered assertion re-calls the
# function and compares the result via `==`, so what matters is whether the
# value itself is a literal, not whether its repr merely parses as one.
# Checked by exact type, not isinstance: a subclass (e.g. a str subclass
# overriding __eq__) can still repr like its builtin base but no longer
# behave like one, which the rendered `== <literal>` assertion needs.
_RENDERABLE_TYPES = (type(None), bool, int, float, str, bytes)
_RENDERABLE_CONTAINER_TYPES = (list, tuple, dict)


def _is_renderable(value):
    if type(value) in _RENDERABLE_TYPES:
        # Still rejects float('nan')/float('inf'): valid objects of a
        # renderable type, but their repr ('nan'/'inf') is a bare name,
        # not a literal, so it wouldn't parse back at all.
        try:
            ast.literal_eval(repr(value))
        except (ValueError, SyntaxError):
            return False
        return True
    if type(value) not in _RENDERABLE_CONTAINER_TYPES:
        return False
    if isinstance(value, dict):
        return all(
            _is_renderable(key) and _is_renderable(val) for key, val in value.items()
        )
    return all(_is_renderable(item) for item in value)


def _call_real_function(module_name, qualname, args, module_cache):
    # Call the real traced function with the AI-proposed arguments. The
    # return value becomes the expected value in the generated assertion --
    # never the LLM's claim about what the output should be.
    module = generator._get_module(module_name, module_cache)
    if module is None:
        return _UNRESOLVED
    try:
        function = getattr(module, qualname)
    except AttributeError:
        return _UNRESOLVED
    try:
        # A deep copy, not the caller's own dict: if the target mutates a
        # mutable argument in place (e.g. xs.append(...)), the caller's copy
        # -- later rendered into the generated test -- must still reflect
        # the originally proposed input, not what the call mutated it into.
        return function(**copy.deepcopy(args))
    except KeyboardInterrupt:
        raise
    except BaseException:  # noqa: BLE001 - not just Exception: a target calling
        # sys.exit() (SystemExit) must be skipped gracefully too, not crash
        # generation -- exceptions aren't rendered as tests yet either way.
        return _RAISED


def _render_test_module(module_name, test_cases_by_function, target_dir):
    function_names = sorted(test_cases_by_function.keys())

    # Avoids colliding with a traced function named `result`, which would
    # otherwise turn `result = result(...)` into an UnboundLocalError.
    result_var = "result"
    while result_var in function_names:
        result_var = "_" + result_var

    lines = [
        _GENERATED_MARKER,
        "import sys",
        "",
        f"sys.path.insert(0, {target_dir!r})",
        f"from {module_name} import {', '.join(function_names)}",
    ]

    # Rendered in the same order functions were verified in (first-appearance
    # order in the trace, preserved by dict insertion order), not
    # alphabetically -- for a module with shared mutable state, an AI test
    # was verified against a real call made in that order, and running the
    # tests out of order would no longer match the value it asserts on.
    for qualname in test_cases_by_function:
        tests = test_cases_by_function[qualname]
        for i, (args, result) in enumerate(tests):
            args_str = ", ".join(f"{name}={value!r}" for name, value in args.items())
            lines += ["", ""]
            lines.append(f"def test_{qualname}_{i}():")
            lines.append(f"    {result_var} = {qualname}({args_str})")
            lines.append(f"    assert {result_var} == {result!r}")

    return "\n".join(lines) + "\n"


def main():
    argv = sys.argv[1:]
    if len(argv) not in (2, 3):
        print(
            "usage: python -m ai_tracer.ai_generator <trace_log> <target_dir> "
            "[output_dir]",
            file=sys.stderr,
        )
        sys.exit(1)
    trace_log_path, target_dir, *rest = argv
    output_dir = rest[0] if len(rest) > 0 else "generated_tests"
    for path in generate_ai_tests(trace_log_path, target_dir, output_dir):
        print(path)


if __name__ == "__main__":
    main()
