import importlib
import inspect
import json
import keyword
import sys
from pathlib import Path

_UNSUPPORTED_PARAM_KINDS = {
    inspect.Parameter.POSITIONAL_ONLY,
    inspect.Parameter.VAR_POSITIONAL,
    inspect.Parameter.VAR_KEYWORD,
}

# First line of every generated test file. Regeneration only ever deletes
# files that carry this exact marker, so a user's own tests (or a target
# module named test_*.py) in the output directory are never touched.
_GENERATED_MARKER = "# generated by ai-tracer - regenerated each run, do not edit"


def _is_valid_import_name(part):
    # str.isidentifier() alone isn't enough: "class".isidentifier() is True,
    # but it's a reserved keyword, so "from class import add" is still a
    # SyntaxError. A traced file can legally be named "class.py" - filenames
    # aren't restricted by Python's keyword list.
    return part.isidentifier() and not keyword.iskeyword(part)


def _contains_array(value):
    # The tracer flattens both lists and tuples to JSON arrays (json has no
    # tuple type), so a recorded array is genuinely ambiguous: rendering it
    # as a list literal silently changes a tuple into a list, and
    # `(1, 2) == [1, 2]` is False, so the generated assertion would fail.
    # Until the trace preserves the distinction, any value containing an
    # array anywhere (including nested inside a dict) can't be reconstructed
    # faithfully.
    if isinstance(value, list):
        return True
    if isinstance(value, dict):
        return any(_contains_array(item) for item in value.values())
    return False


def _is_generated_file(path):
    # A file is ours to delete or overwrite only if its very first line is the
    # marker we write. Reading just the first line keeps this cheap and avoids
    # being fooled by the marker text appearing lower down in an unrelated file.
    try:
        with path.open(encoding="utf-8") as fh:
            return fh.readline().rstrip("\n") == _GENERATED_MARKER
    except (OSError, UnicodeDecodeError):
        return False


def _would_clobber(path):
    # True if writing here would destroy a file we didn't generate. A
    # non-existent path, or one carrying our own marker, is safe to write.
    return path.exists() and not _is_generated_file(path)


def _is_importable_package_dir(path):
    # A regular package (has __init__.py) or a namespace package (no
    # __init__.py, but a directory that still contributes importable modules).
    # Checking for any direct .py file catches the common namespace-package
    # layout without trying to resolve arbitrarily nested namespace-only trees.
    if (path / "__init__.py").is_file():
        return True
    return any(child.suffix == ".py" for child in path.iterdir())


def _local_module_names(target_dir):
    # Every top-level name the target dir makes importable: each .py file's
    # stem, and each subdirectory that's a package (regular or namespace).
    # "conftest" is excluded: it's pytest's own infrastructure, never imported
    # as a target module by name, and evicting it would delete the conftest
    # pytest is actively importing (the generated conftest itself, or an
    # ancestor one), aborting collection with a KeyError.
    names = set()
    for entry in Path(target_dir).iterdir():
        if entry.is_file() and entry.suffix == ".py":
            names.add(entry.stem)
        elif entry.is_dir() and _is_importable_package_dir(entry):
            names.add(entry.name)
    names.discard("conftest")
    return names


def generate(trace_log_path, target_dir, output_dir="generated_tests"):
    calls = json.loads(Path(trace_log_path).read_text())
    target_dir = str(Path(target_dir).resolve())

    calls_by_module = {}
    module_cache = {}
    signature_cache = {}

    # Snapshot sys.path and sys.modules so anything a target module changes at
    # import time (a module that inserts its own sys.path entry, say) and every
    # module imported while inspecting target code is undone afterward, keeping
    # repeated generate() calls in one process hermetic. Restoring the whole
    # snapshot also can't raise the way a lone list.remove(target_dir) could if
    # the target had already removed that entry itself.
    original_sys_path = list(sys.path)
    original_sys_modules = dict(sys.modules)
    sys.path.insert(0, target_dir)
    # Evict every name the target dir defines, not just the module under
    # test, so a target sibling (e.g. a local inspect.py, or a module cached
    # from a previous generate() call) wins over a stale/stdlib module of the
    # same name - matching how the CLI runs the target in the first place.
    # Also evict any already-cached submodule of a local package ("pkg.a"),
    # so a stale submodule can't be reused without re-importing; the package
    # is then imported fresh once and its "pkg.a"/"pkg.b" submodules build on
    # that single import, exactly as a normal run would.
    local_names = _local_module_names(target_dir)
    for name in list(sys.modules):
        if name.split(".")[0] in local_names:
            sys.modules.pop(name, None)
    try:
        for call in calls:
            reason = _skip_reason(call, module_cache, signature_cache)
            if reason is None:
                calls_by_module.setdefault(call["module"], []).append(call)
            else:
                print(
                    f"Skipping {call['module']}.{call['qualname']}: {reason}",
                    file=sys.stderr,
                )
    finally:
        sys.path[:] = original_sys_path
        sys.modules.clear()
        sys.modules.update(original_sys_modules)

    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True, parents=True)

    # Clear previously generated tests before writing this run's, so a module
    # that's no longer generatable (its calls now all skipped, or gone from
    # the trace) doesn't leave a stale test_*.py behind for pytest to run.
    # Only files carrying our own marker are removed, so a user's hand-written
    # tests (or a target module named test_*.py) sharing this directory are
    # never deleted, even when output_dir points at an existing test folder.
    for existing in output_path.glob("test_*.py"):
        if _is_generated_file(existing):
            existing.unlink()

    # A single conftest.py does the import setup once for the whole generated
    # test session: it puts target_dir on sys.path and evicts any target-local
    # name cached under the same identity. Doing this once (not in every test
    # file) is what keeps it correct: a shared module or package is imported
    # exactly once, so its import-time state stays consistent across files,
    # while a stale or shadowing same-named module is still cleared first. Only
    # written if it wouldn't clobber a conftest.py the user already keeps here;
    # each test file also inserts target_dir itself, so imports still resolve
    # even when this conftest is skipped.
    conftest_path = output_path / "conftest.py"
    if _would_clobber(conftest_path):
        print(
            f"Not writing {conftest_path}: a conftest.py that ai-tracer didn't "
            "generate is already there. The generated tests still import the "
            "target via their own sys.path setup, but the one-time eviction of "
            "stale/shadowing same-named modules is skipped, so if this pytest "
            "session already cached a module sharing a top-level name with the "
            "target, imports could resolve to it. Use an empty output directory "
            "(the default generated_tests/) to get the full setup.",
            file=sys.stderr,
        )
    else:
        conftest_path.write_text(_render_conftest(target_dir))

    # Assign file names in sorted order (deterministic) and append a numeric
    # suffix to avoid two kinds of clash: two module names that flatten to the
    # same file ("pkg.sub" and "pkg_sub" both want test_pkg_sub.py), and an
    # existing file we mustn't clobber - a user's own unmarked test_helper.py
    # sharing this directory. A file already carrying our marker is fair game
    # to overwrite (it's a stale generated file for this same module).
    used_names = {}
    written_paths = []
    for module_name in sorted(calls_by_module):
        base = f"test_{module_name.replace('.', '_')}"
        file_name = f"{base}.py"
        suffix = 1
        while file_name in used_names or _would_clobber(output_path / file_name):
            file_name = f"{base}_{suffix}.py"
            suffix += 1
        used_names[file_name] = module_name
        test_path = output_path / file_name
        test_path.write_text(
            _render_test_module(module_name, calls_by_module[module_name], target_dir)
        )
        written_paths.append(test_path)

    return written_paths


def _skip_reason(call, module_cache, signature_cache):
    # Returns None if the call can be generated, otherwise a short,
    # human-readable reason it's being skipped - printed to stderr by the
    # caller so a run's output makes it obvious what didn't make it into
    # generated_tests/ and why, rather than silently doing nothing.

    # Only plain top-level functions for now: qualname.isidentifier() is
    # False for methods ("ClassName.method"), nested functions
    # ("outer.<locals>.inner"), and lambdas ("<lambda>") alike.
    if not call["qualname"].isidentifier():
        return "not a plain top-level function (method, nested function, or lambda)"
    # The entry script is always recorded as module "__main__" (matching
    # direct execution - see the tracer's own module resolution), but
    # "__main__" isn't a name this process can re-import to mean "the
    # traced script": it would resolve to whatever *this* process's own
    # entry point happens to be. Generating tests for the entry script's
    # own functions needs its real file path, which a bare trace log
    # doesn't carry - deferred to the PR that wires trace+generate
    # together, where the CLI already has that path.
    if call["module"] == "__main__":
        return "the entry script's own functions aren't generatable yet (module \"__main__\" has no real import path)"
    # A target that rebinds its own __name__ to a JSON-safe non-string (e.g.
    # __name__ = 123) is recorded verbatim by the tracer, so guard before
    # treating module as a dotted string.
    if not isinstance(call["module"], str) or not all(
        _is_valid_import_name(part) for part in call["module"].split(".")
    ):
        return f"module {call['module']!r} is not a valid import target"
    # A call still in progress when tracing stopped (a worker thread the main
    # script never joined) is written by tracer.stop() before its return event
    # fires, so it has no raised/return_* fields. It never produced an outcome
    # to assert - skip it rather than crash on the missing keys below.
    if "raised" not in call:
        return (
            "call didn't finish before tracing stopped (e.g. an unjoined worker thread)"
        )
    # Non-JSON (repr-fallback) values are never reconstructable as a
    # literal, don't generate a test that's likely to be wrong.
    if any(kind != "json" for kind in call["arg_serialization"].values()):
        return "one or more arguments could not be captured as a JSON value"
    if call["raised"]:
        return "call raised an exception, not supported yet"
    # raised is False here, so return_serialization is "json" (a real JSON
    # value), "repr" (a non-serializable value we can't reconstruct as a
    # literal), or None (a genuine None return, which json.dumps handles as
    # `null` and is a perfectly safe literal). Only "repr" is unusable.
    if call["return_serialization"] == "repr":
        return "return value could not be captured as a JSON value"
    if any(_contains_array(value) for value in call["args"].values()):
        return "an argument contains a list/array (a tuple can't be told apart from a list in the trace yet)"
    if _contains_array(call["return_value"]):
        return "return value contains a list/array (a tuple can't be told apart from a list in the trace yet)"
    # Importing re-executes the module's top-level code, which can raise
    # anything, including whatever originally crashed the target program
    # (the tracer writes the trace log even when the target crashed). Check
    # this once, with a specific message, rather than let a confusing
    # failure surface deeper in the signature check below.
    if _get_module(call["module"], module_cache) is None:
        return (
            f"module {call['module']!r} could not be imported (it may raise on import)"
        )
    signature = _get_signature(
        call["module"], call["qualname"], module_cache, signature_cache
    )
    if signature is None:
        return (
            "function no longer exists, or can't be replayed as a plain "
            "synchronous call (async, generator, positional-only, *args, or "
            "**kwargs)"
        )
    # Even a supported signature may no longer accept the recorded argument
    # names (the function was renamed, its parameters changed, a new required
    # one was added). Binding the recorded names against the current
    # signature catches that here, instead of emitting a test that fails the
    # moment it calls the function.
    try:
        signature.bind(**dict.fromkeys(call["args"]))
    except TypeError:
        return "recorded arguments no longer match the function's signature"
    return None


def _get_module(module_name, module_cache):
    # Cached per generate() call (not a module-level global, which would leak
    # imported target modules across separate calls), so a module referenced
    # by many calls is only imported, and its top-level code only
    # re-executed, once. generate() has already evicted the target dir's own
    # names from sys.modules up front, so this first import is fresh; a
    # package's submodules then build on that single package import the same
    # way a normal run would, without re-running its __init__.py per submodule.
    if module_name not in module_cache:
        try:
            module_cache[module_name] = importlib.import_module(module_name)
        except KeyboardInterrupt:
            # Left to propagate so the user can still cancel a run.
            raise
        except BaseException:  # noqa: BLE001 - target import can raise anything
            # Importing re-runs the target's top-level code, which can raise
            # anything - not just Exception but BaseException subclasses too
            # (SystemExit from a module that calls sys.exit() or parses args at
            # import, GeneratorExit, asyncio.CancelledError). All of them mean
            # "not safely importable now", not "abort the whole generation run".
            module_cache[module_name] = None
    return module_cache[module_name]


def _get_signature(module_name, qualname, module_cache, signature_cache):
    # Returns the current inspect.Signature for a generatable function, or
    # None if it no longer exists, can't be introspected, or uses a
    # parameter kind we can't replay with plain keyword arguments
    # (positional-only, *args, **kwargs). Cached by (module, qualname) - the
    # signature is a property of the function, independent of any one call's
    # arguments, so the per-call argument binding is checked separately.
    key = (module_name, qualname)
    if key not in signature_cache:
        module = _get_module(module_name, module_cache)
        try:
            function = getattr(module, qualname)
            signature = inspect.signature(function)
        except (AttributeError, TypeError, ValueError):
            signature_cache[key] = None
        else:
            # A coroutine/generator/async-generator function returns a
            # coroutine or (async) generator object when called, not the
            # value the tracer recorded (which it captured on await/resume),
            # so a plain synchronous `result = f(...)` test never matches.
            not_plainly_callable = (
                inspect.iscoroutinefunction(function)
                or inspect.isgeneratorfunction(function)
                or inspect.isasyncgenfunction(function)
            )
            has_unsupported_kind = any(
                p.kind in _UNSUPPORTED_PARAM_KINDS
                for p in signature.parameters.values()
            )
            signature_cache[key] = (
                None if not_plainly_callable or has_unsupported_kind else signature
            )
    return signature_cache[key]


def _render_conftest(target_dir):
    # Runs once, before pytest collects any generated test file. Puts the
    # target dir on sys.path and evicts every target-local name (modules and
    # packages alike) that's cached under the same identity, so each test then
    # imports the target's own module rather than a stale or shadowing
    # same-named one. Doing the eviction exactly once here - rather than in
    # every test file - is what makes it safe to evict packages too: the
    # target's modules are each imported a single time for the whole session,
    # so import-time state a module or package sets up stays consistent across
    # every test that depends on it.
    local = sorted(_local_module_names(target_dir))
    lines = [
        _GENERATED_MARKER,
        "import sys",
        "",
        f"sys.path.insert(0, {target_dir!r})",
        "",
        "# Clear every cached module whose top-level name the target dir defines",
        "# - the module itself, a sibling it imports, a package and any of its",
        "# already-cached submodules (popping just the package root would leave",
        "# a stale pkg.sub behind). Matches how ai-tracer imports target code.",
        "# Skip this conftest's own top-level package: when the output dir is a",
        "# package under the target dir (e.g. tests/ with an __init__.py), its",
        "# name is target-local too, and deleting it would evict this very",
        "# module while pytest is importing it, aborting collection.",
        f"_local = {tuple(local)!r}",
        "_own = __name__.split('.')[0]",
        "for _name in list(sys.modules):",
        "    _top = _name.split('.')[0]",
        "    if _top in _local and _top != _own:",
        "        del sys.modules[_name]",
    ]
    return "\n".join(lines) + "\n"


def _render_test_module(module_name, module_calls, target_dir):
    imported_names = sorted({call["qualname"] for call in module_calls})
    # A variable that can't collide with any function this file imports: a
    # traced function named `result` would otherwise turn `result = result(...)`
    # into an assignment to a local named `result`, so the call on the right
    # raises UnboundLocalError instead of invoking the imported function.
    result_var = "result"
    while result_var in imported_names:
        result_var = "_" + result_var

    # The conftest.py generated alongside this file evicts stale/shadowing
    # target modules once for the whole session; this per-file sys.path.insert
    # is a fallback so imports still resolve if that conftest was skipped (the
    # user already had one) or the file is run on its own.
    lines = [
        _GENERATED_MARKER,
        "import sys",
        "",
        f"sys.path.insert(0, {target_dir!r})",
        f"from {module_name} import {', '.join(imported_names)}",
    ]

    call_counts = {}
    for call in module_calls:
        qualname = call["qualname"]
        index = call_counts.get(qualname, 0)
        call_counts[qualname] = index + 1

        args = ", ".join(f"{name}={value!r}" for name, value in call["args"].items())
        lines += ["", ""]
        lines.append(f"def test_{qualname}_{index}():")
        lines.append(f"    {result_var} = {qualname}({args})")
        lines.append(f"    assert {result_var} == {call['return_value']!r}")

    return "\n".join(lines) + "\n"


def main():
    argv = sys.argv[1:]
    if len(argv) not in (2, 3):
        print(
            "usage: python -m ai_tracer.generator <trace_log> <target_dir> [output_dir]",
            file=sys.stderr,
        )
        sys.exit(1)
    trace_log_path, target_dir, *rest = argv
    output_dir = rest[0] if rest else "generated_tests"
    for path in generate(trace_log_path, target_dir, output_dir):
        print(path)


if __name__ == "__main__":
    main()
