import builtins
import importlib
import importlib.util
import inspect
import json
import keyword
import os
import sys
from pathlib import Path

from ai_tracer import mocker

_UNSUPPORTED_PARAM_KINDS = {
    inspect.Parameter.POSITIONAL_ONLY,
    inspect.Parameter.VAR_POSITIONAL,
    inspect.Parameter.VAR_KEYWORD,
}

# Regeneration only deletes files starting with this exact line, so a
# user's own tests in the output directory are never touched.
_GENERATED_MARKER = "# generated by ai-tracer - regenerated each run, do not edit"

# The synthetic name the entry script is loaded under (both here and in the
# generated test file) - not "__main__", so its own guard doesn't re-run.
_ENTRY_MODULE_IMPORT_NAME = "_ai_tracer_entry_script"


def _is_valid_import_name(part):
    # "class".isidentifier() is True but it's a keyword, so
    # "from class import add" is still a SyntaxError.
    return part.isidentifier() and not keyword.iskeyword(part)


def _contains_array(value):
    # Lists and tuples both trace as JSON arrays, so a recorded array is
    # ambiguous: rendering it as a list could turn a tuple into one and
    # fail the generated assertion. Skip anything containing an array.
    if isinstance(value, list):
        return True
    if isinstance(value, dict):
        return any(_contains_array(item) for item in value.values())
    return False


def _is_generated_file(path):
    # Only the first line is checked, so this stays cheap and can't be
    # fooled by the marker text appearing lower in an unrelated file.
    # Recognizes ai_generator's marker too (imported lazily to avoid a
    # circular import at module load time), so a stale test_*_ai.py from a
    # previous --ai run still gets cleaned up on a run without --ai.
    from ai_tracer import ai_generator

    try:
        with path.open(encoding="utf-8") as fh:
            first_line = fh.readline().rstrip("\n")
    except (OSError, UnicodeDecodeError):
        return False
    return first_line in (_GENERATED_MARKER, ai_generator._GENERATED_MARKER)


def _would_clobber(path):
    return path.exists() and not _is_generated_file(path)


def _is_importable_package_dir(path):
    # Regular package (__init__.py) or namespace package (any .py file
    # directly inside, even without __init__.py).
    if (path / "__init__.py").is_file():
        return True
    return any(child.suffix == ".py" for child in path.iterdir())


def _local_module_names(target_dir):
    # "conftest" and "pytest" are excluded even if the target defines a
    # same-named file/package: evicting "conftest" mid-collection would
    # delete the conftest pytest is importing, and evicting "pytest" would
    # make a generated `import pytest` (used to render pytest.raises(...))
    # resolve to the target's own module instead of the real package, since
    # target_dir is on sys.path ahead of everything else by then. Same
    # tradeoff as "conftest" above: a target that legitimately defines its
    # own same-named module can't have it freshly re-imported here, since
    # both names are reserved for pytest's own infrastructure by the time
    # any of this runs.
    names = set()
    for entry in Path(target_dir).iterdir():
        if entry.is_file() and entry.suffix == ".py":
            names.add(entry.stem)
        elif entry.is_dir() and _is_importable_package_dir(entry):
            names.add(entry.name)
    names.discard("conftest")
    names.discard("pytest")
    return names


def generate(
    trace_log_path,
    target_dir,
    output_dir="generated_tests",
    entry_script=None,
    ai=False,
):
    calls = json.loads(Path(trace_log_path).read_text())
    target_dir = str(Path(target_dir).resolve())
    if entry_script is not None:
        entry_script = str(Path(entry_script).resolve())
    # Resolved before importing target code: a module that chdir()s at
    # import time would otherwise send a relative output_dir there instead.
    output_path = Path(output_dir).resolve()

    calls_by_module = {}
    module_cache = {}
    signature_cache = {}
    children_by_call_id = _children_by_call_id(calls)

    # Snapshot sys.path/sys.modules/cwd so anything target imports change
    # (sys.path entries, os.chdir(), cached modules) is undone afterward,
    # keeping repeated generate() calls in one process hermetic.
    original_sys_path = list(sys.path)
    original_sys_modules = dict(sys.modules)
    original_cwd = os.getcwd()
    sys.path.insert(0, target_dir)
    # Evict every name the target dir defines (not just the module under
    # test) so a same-named stale/stdlib module never wins, and evict any
    # cached submodule of a local package so it's re-imported fresh too.
    local_names = _local_module_names(target_dir)
    for name in list(sys.modules):
        if name.split(".")[0] in local_names:
            sys.modules.pop(name, None)
    try:
        if entry_script is not None:
            module_cache["__main__"] = _load_entry_module(entry_script)
        for call in calls:
            reason = _skip_reason(call, module_cache, signature_cache)
            if reason is None:
                reason = _unmockable_child_reason(
                    call, children_by_call_id, module_cache
                )
            if reason is None:
                calls_by_module.setdefault(call["module"], []).append(call)
            else:
                print(
                    f"Skipping {call['module']}.{call['qualname']}: {reason}",
                    file=sys.stderr,
                )
    finally:
        sys.path[:] = original_sys_path
        sys.modules.clear()
        sys.modules.update(original_sys_modules)
        os.chdir(original_cwd)

    output_path.mkdir(exist_ok=True, parents=True)

    # Clear previously generated tests first, so a module that's no longer
    # generatable doesn't leave a stale test_*.py for pytest to run. Only
    # files carrying our marker are removed.
    for existing in output_path.glob("test_*.py"):
        if _is_generated_file(existing):
            existing.unlink()

    # A single conftest.py does the import setup once for the whole session
    # (puts target_dir on sys.path, evicts stale/shadowing modules), so a
    # shared package is only imported once across every generated test file.
    conftest_path = output_path / "conftest.py"
    if _would_clobber(conftest_path):
        print(
            f"Not writing {conftest_path}: a conftest.py that ai-tracer didn't "
            "generate is already there. The generated tests still import the "
            "target via their own sys.path setup, but the one-time eviction of "
            "stale/shadowing same-named modules is skipped, so if this pytest "
            "session already cached a module sharing a top-level name with the "
            "target, imports could resolve to it. Use an empty output directory "
            "(the default generated_tests/) to get the full setup.",
            file=sys.stderr,
        )
    else:
        conftest_path.write_text(_render_conftest(target_dir))

    # Numeric suffix avoids two clashes: module names flattening to the same
    # file ("pkg.sub" vs "pkg_sub"), and an existing unmarked file we
    # mustn't clobber.
    used_names = {}
    written_paths = []
    for module_name in sorted(calls_by_module):
        base = f"test_{module_name.replace('.', '_')}"
        file_name = f"{base}.py"
        suffix = 1
        while file_name in used_names or _would_clobber(output_path / file_name):
            file_name = f"{base}_{suffix}.py"
            suffix += 1
        used_names[file_name] = module_name
        test_path = output_path / file_name
        test_path.write_text(
            _render_test_module(
                module_name,
                calls_by_module[module_name],
                target_dir,
                children_by_call_id,
                entry_script,
            )
        )
        written_paths.append(test_path)

    if ai:
        from ai_tracer import ai_generator

        written_paths.extend(
            ai_generator.generate_ai_tests(trace_log_path, target_dir, output_dir)
        )

    return written_paths


def _skip_reason(call, module_cache, signature_cache):
    # None if the call can be generated, else a reason printed to stderr.
    if not call["qualname"].isidentifier():
        return "not a plain top-level function (method, nested function, or lambda)"
    # "__main__" can only be resolved to the traced script if generate()
    # was given its file path (module_cache is pre-populated in that case).
    if call["module"] == "__main__" and "__main__" not in module_cache:
        return "the entry script's own functions need its file path (trace and generate together to get this)"
    # A target can rebind __name__ to a non-string; guard before treating
    # module as a dotted string.
    if not isinstance(call["module"], str) or not all(
        _is_valid_import_name(part) for part in call["module"].split(".")
    ):
        return f"module {call['module']!r} is not a valid import target"
    # An unjoined worker thread's call can be written before its return
    # event fires, with no raised/return_* fields.
    if "raised" not in call:
        return (
            "call didn't finish before tracing stopped (e.g. an unjoined worker thread)"
        )
    if any(kind != "json" for kind in call["arg_serialization"].values()):
        return "one or more arguments could not be captured as a JSON value"
    if any(_contains_array(value) for value in call["args"].values()):
        return "an argument contains a list/array (a tuple can't be told apart from a list in the trace yet)"
    if not call["raised"]:
        if call["return_serialization"] == "repr":
            return "return value could not be captured as a JSON value"
        if _contains_array(call["return_value"]):
            return "return value contains a list/array (a tuple can't be told apart from a list in the trace yet)"
    # Checked before the exception's own module: if the two are involved in
    # a circular import, importing the function's module first can succeed
    # where importing the exception module cold would fail.
    if _get_module(call["module"], module_cache) is None:
        return (
            f"module {call['module']!r} could not be imported (it may raise on import)"
        )
    if call["raised"]:
        exception_reason = _exception_skip_reason(call, module_cache)
        if exception_reason is not None:
            return exception_reason
    signature = _get_signature(
        call["module"], call["qualname"], module_cache, signature_cache
    )
    if signature is None:
        return (
            "function no longer exists, or can't be replayed as a plain "
            "synchronous call (async, generator, positional-only, *args, or "
            "**kwargs)"
        )
    # A supported signature may still have been renamed/changed since tracing.
    try:
        signature.bind(**dict.fromkeys(call["args"]))
    except TypeError:
        return "recorded arguments no longer match the function's signature"
    return None


def _exception_skip_reason(call, module_cache):
    # None if the exception can be named in a `pytest.raises(...)`, else a
    # skip reason.
    exception_type = call["exception_type"]
    exception_module = call["exception_module"]
    if not isinstance(exception_type, str) or not _is_valid_import_name(exception_type):
        return f"exception type {exception_type!r} is not a plain identifier"
    if exception_module == "builtins":
        if not hasattr(builtins, exception_type):
            return f"exception {exception_type!r} is not a builtin"
        return None
    if exception_module == "__main__":
        # Only handled when the raising function is also in the entry
        # script and generate() was given its path - a helper module
        # referencing an entry-script exception class stays unsupported.
        if call["module"] != "__main__" or "__main__" not in module_cache:
            return (
                "exception module '__main__' can only be named when the "
                "raising function is also in the entry script and its file "
                "path was given"
            )
        module = module_cache["__main__"]
        if module is None or not hasattr(module, exception_type):
            return f"exception __main__.{exception_type} could not be imported"
        return None
    if not isinstance(exception_module, str) or not all(
        _is_valid_import_name(part) for part in exception_module.split(".")
    ):
        return f"exception module {exception_module!r} is not a valid import target"
    module = _get_module(exception_module, module_cache)
    if module is None or not hasattr(module, exception_type):
        return f"exception {exception_module}.{exception_type} could not be imported"
    return None


def _children_by_call_id(calls):
    # A call's direct children, keyed by its own call_id. Grouped over every
    # recorded call, not just generatable ones, so a lookup for any call_id
    # in the trace resolves correctly regardless of whether that call itself
    # ended up generatable.
    children = {}
    for call in calls:
        parent_call_id = call["parent_call_id"]
        if parent_call_id is not None:
            children.setdefault(parent_call_id, []).append(call)
    return children


def _mock_skip_reason(call, module_cache):
    # None if `call` is safe to stand in for as a mocked child (its recorded
    # return value or exception can be reproduced without replaying the real
    # call), else a reason. Doesn't look at the child's own arguments at all
    # - mocking replaces the whole call, so what it was passed never matters,
    # only what it handed back.
    if not call["qualname"].isidentifier():
        return "not a plain top-level function (method, nested function, or lambda)"
    if not isinstance(call["module"], str) or not all(
        _is_valid_import_name(part) for part in call["module"].split(".")
    ):
        return f"module {call['module']!r} is not a valid import target"
    if "raised" not in call:
        return (
            "call didn't finish before tracing stopped (e.g. an unjoined worker thread)"
        )
    if call["raised"]:
        return _exception_skip_reason(call, module_cache)
    if call["return_serialization"] == "repr":
        return "return value could not be captured as a JSON value"
    if _contains_array(call["return_value"]):
        return "return value contains a list/array (a tuple can't be told apart from a list in the trace yet)"
    return None


def _unmockable_child_reason(call, children_by_call_id, module_cache):
    # None if every direct child of `call` is a safe mock target, else a
    # reason naming the first one that isn't. Only direct children matter:
    # mocking a child replaces its whole body, so anything nested inside it
    # never runs during the generated test either.
    for child in children_by_call_id.get(call["call_id"], []):
        reason = _mock_skip_reason(child, module_cache)
        if reason is not None:
            return (
                f"child call {child['module']}.{child['qualname']} can't be "
                f"mocked: {reason}"
            )
    return None


def _get_module(module_name, module_cache):
    # Cached per generate() call so a module referenced by many calls is
    # only imported (and its top-level code only re-run) once.
    if module_name not in module_cache:
        try:
            module_cache[module_name] = importlib.import_module(module_name)
        except KeyboardInterrupt:
            raise
        except BaseException:  # noqa: BLE001 - target import can raise anything
            # Not just Exception - SystemExit/GeneratorExit etc. all just
            # mean "not importable now", not "abort the whole run".
            module_cache[module_name] = None
    return module_cache[module_name]


def _load_entry_module(entry_script):
    # Loaded under a synthetic name so the entry script's own
    # `if __name__ == "__main__":` guard doesn't refire during exec_module;
    # patched to the real "__main__" right after, so a function reading
    # __name__ at call time still sees what it saw when traced.
    try:
        spec = importlib.util.spec_from_file_location(
            "_ai_tracer_entry_script", entry_script
        )
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        module.__name__ = "__main__"
    except KeyboardInterrupt:
        raise
    except BaseException:  # noqa: BLE001 - target import can raise anything
        return None
    return module


def _get_signature(module_name, qualname, module_cache, signature_cache):
    # Current inspect.Signature for a generatable function, or None if it no
    # longer exists, can't be introspected, or uses an unreplayable
    # parameter kind. Cached by (module, qualname).
    key = (module_name, qualname)
    if key not in signature_cache:
        module = _get_module(module_name, module_cache)
        try:
            function = getattr(module, qualname)
            signature = inspect.signature(function)
        except KeyboardInterrupt:
            raise
        except BaseException:  # noqa: BLE001 - target hooks can raise anything
            # getattr/__getattr__ and inspect.signature/__signature__ are
            # target code and can raise anything; treat as not introspectable.
            signature_cache[key] = None
        else:
            # A coroutine/generator function returns that kind of object,
            # not the value the tracer recorded on await/resume.
            not_plainly_callable = (
                inspect.iscoroutinefunction(function)
                or inspect.isgeneratorfunction(function)
                or inspect.isasyncgenfunction(function)
            )
            has_unsupported_kind = any(
                p.kind in _UNSUPPORTED_PARAM_KINDS
                for p in signature.parameters.values()
            )
            signature_cache[key] = (
                None if not_plainly_callable or has_unsupported_kind else signature
            )
    return signature_cache[key]


def _render_conftest(target_dir):
    # Runs once per session, before any generated test file is collected:
    # puts target_dir on sys.path and evicts stale/shadowing target-local
    # modules, so a shared package is imported exactly once per session.
    local = sorted(_local_module_names(target_dir))
    lines = [
        _GENERATED_MARKER,
        "import sys",
        "",
        f"sys.path.insert(0, {target_dir!r})",
        "",
        "# Evict cached target-local modules/packages/submodules so tests",
        "# import fresh copies. Spare this conftest's own ancestor chain -",
        "# deleting it mid-import would abort collection with a KeyError.",
        f"_local = {tuple(local)!r}",
        "_keep = {__name__}",
        "_parent = __name__",
        "while '.' in _parent:",
        "    _parent = _parent.rsplit('.', 1)[0]",
        "    _keep.add(_parent)",
        "for _name in list(sys.modules):",
        "    if _name.split('.')[0] in _local and _name not in _keep:",
        "        del sys.modules[_name]",
    ]
    return "\n".join(lines) + "\n"


def _mocked_child_groups(module_calls, children_by_call_id):
    # call_id -> [(child qualname, [calls to it, in traced order]), ...],
    # in first-appearance order, for every call in this module that has at
    # least one direct child. A parent with no children is left out
    # entirely, not mapped to an empty list.
    groups_by_call_id = {}
    for call in module_calls:
        children = children_by_call_id.get(call["call_id"], [])
        if not children:
            continue
        order = []
        grouped = {}
        for child in children:
            qualname = child["qualname"]
            if qualname not in grouped:
                grouped[qualname] = []
                order.append(qualname)
            grouped[qualname].append(child)
        groups_by_call_id[call["call_id"]] = [
            (qualname, grouped[qualname]) for qualname in order
        ]
    return groups_by_call_id


def _render_test_module(
    module_name, module_calls, target_dir, children_by_call_id, entry_script=None
):
    imported_names = sorted({call["qualname"] for call in module_calls})
    # Avoids colliding with a traced function named `result`, which would
    # otherwise turn `result = result(...)` into an UnboundLocalError.
    result_var = "result"
    while result_var in imported_names:
        result_var = "_" + result_var

    mocked_groups_by_call_id = _mocked_child_groups(module_calls, children_by_call_id)
    any_mocked = bool(mocked_groups_by_call_id)
    mocked_children = [
        child
        for groups in mocked_groups_by_call_id.values()
        for _, calls in groups
        for child in calls
    ]

    has_raises = any(call["raised"] for call in module_calls)
    has_builtin_raises = any(
        call["raised"] and call["exception_module"] == "builtins"
        for call in module_calls
    ) or any(
        child["raised"] and child["exception_module"] == "builtins"
        for child in mocked_children
    )
    # pytest/builtins/exception modules are imported under reserved aliases
    # (never a bare name), so a traced function named e.g. `pytest` or
    # `errors` can't shadow them.
    reserved = set(imported_names)
    if any_mocked:
        # "from unittest import mock" has no alias of its own (mocker.py's
        # fixed rendering), so this only guards *other* reserved names from
        # picking "mock" - a traced function literally named `mock` is a
        # pre-existing, accepted collision with that fixed import.
        reserved.add("mock")

    def _reserve(base):
        alias = base
        while alias in reserved:
            alias = "_" + alias
        reserved.add(alias)
        return alias

    pytest_alias = _reserve("_raises_pytest") if has_raises else None
    builtins_alias = _reserve("_raises_builtins") if has_builtin_raises else None
    is_entry_script = module_name == "__main__"
    # A mocked call's own module is used as the mock.patch() target, but
    # "__main__" as a plain string would resolve to whatever this pytest
    # process's real entry point is, not the reloaded copy - the synthetic
    # name it's registered under below is used instead in that case.
    mock_parent_module = _ENTRY_MODULE_IMPORT_NAME if is_entry_script else module_name
    # A mocked child's raised exception can live in "__main__" even when
    # this test file's own module doesn't - e.g. a helper module calling an
    # entry-script function that raises - so entry_module_var may be needed
    # here purely to name that exception, without the entry-script-reload
    # machinery below driving imported_names too.
    needs_entry_module = is_entry_script or any(
        child["raised"] and child["exception_module"] == "__main__"
        for child in mocked_children
    )
    entry_util_alias = _reserve("_importlib_util") if needs_entry_module else None
    entry_spec_var = _reserve("_entry_spec") if needs_entry_module else None
    entry_module_var = _reserve("_entry_module") if needs_entry_module else None
    exception_modules = sorted(
        {
            call["exception_module"]
            for call in module_calls
            # "__main__" is referenced through entry_module_var instead of
            # a plain import (which would import this test process's own
            # entry point, not the traced script).
            if call["raised"]
            and call["exception_module"] not in ("builtins", "__main__")
        }
        | {
            child["exception_module"]
            for child in mocked_children
            if child["raised"]
            and child["exception_module"] not in ("builtins", "__main__")
        }
    )
    exception_aliases = {
        exception_module: _reserve("_raises_" + exception_module.replace(".", "_"))
        for exception_module in exception_modules
    }

    def _mock_exception_reference(child_call):
        return _exception_reference(
            child_call, builtins_alias, exception_aliases, entry_module_var
        )

    mock_aliases = {
        (call_id, qualname): _reserve(f"_mock_{qualname}")
        for call_id, groups in mocked_groups_by_call_id.items()
        for qualname, _ in groups
    }

    # This sys.path.insert is a fallback for when the generated conftest.py
    # was skipped or the file is run on its own.
    lines = [_GENERATED_MARKER, "import sys"]
    if has_raises:
        lines.append(f"import pytest as {pytest_alias}")
    if has_builtin_raises:
        lines.append(f"import builtins as {builtins_alias}")
    if any_mocked:
        lines.append(mocker.render_import_line())
    if needs_entry_module:
        lines.append(f"import importlib.util as {entry_util_alias}")
    lines += ["", f"sys.path.insert(0, {target_dir!r})"]
    if needs_entry_module:
        # Loaded under a synthetic name, not "__main__", so the entry
        # script's own `if __name__ == "__main__":` guard doesn't re-run.
        lines.append(
            f"{entry_spec_var} = {entry_util_alias}.spec_from_file_location("
            f"{_ENTRY_MODULE_IMPORT_NAME!r}, {entry_script!r})"
        )
        lines.append(
            f"{entry_module_var} = {entry_util_alias}.module_from_spec({entry_spec_var})"
        )
        lines.append(f"{entry_spec_var}.loader.exec_module({entry_module_var})")
        # Patched back to "__main__" after exec so a function reading
        # __name__ at call time sees what it saw when traced.
        lines.append(f'{entry_module_var}.__name__ = "__main__"')
    if is_entry_script:
        if any_mocked:
            # mock.patch() resolves its string target via sys.modules, and
            # this process's real "__main__" is pytest's own entry point,
            # not this reloaded copy - registered under the synthetic name
            # instead so a mocked entry-script call's own children resolve
            # to the copy actually running these tests.
            lines.append(
                f"sys.modules[{_ENTRY_MODULE_IMPORT_NAME!r}] = {entry_module_var}"
            )
        for name in imported_names:
            lines.append(f"{name} = {entry_module_var}.{name}")
    else:
        # Imported before any exception module - see the circular-import
        # note in _skip_reason above.
        lines.append(f"from {module_name} import {', '.join(imported_names)}")
    for exception_module in exception_modules:
        lines.append(
            f"import {exception_module} as {exception_aliases[exception_module]}"
        )

    call_counts = {}
    for call in module_calls:
        qualname = call["qualname"]
        index = call_counts.get(qualname, 0)
        call_counts[qualname] = index + 1

        args = ", ".join(f"{name}={value!r}" for name, value in call["args"].items())
        lines += ["", ""]
        lines.append(f"def test_{qualname}_{index}():")
        if call["raised"]:
            reference = _exception_reference(
                call, builtins_alias, exception_aliases, entry_module_var
            )
            body = [
                f"with {pytest_alias}.raises({reference}):",
                f"    {qualname}({args})",
            ]
        else:
            body = [
                f"{result_var} = {qualname}({args})",
                f"assert {result_var} == {call['return_value']!r}",
            ]

        groups = mocked_groups_by_call_id.get(call["call_id"])
        if groups is None:
            indent = "    "
        else:
            clauses = [
                mocker.render_patch_clause(
                    mock_parent_module,
                    calls,
                    mock_aliases[(call["call_id"], qualname_)],
                    _mock_exception_reference,
                )
                for qualname_, calls in groups
            ]
            lines.append(f"    {mocker.render_patch_statement(clauses)}")
            indent = "        "
        for body_line in body:
            lines.append(f"{indent}{body_line}")

    return "\n".join(lines) + "\n"


def _exception_reference(call, builtins_alias, exception_aliases, entry_module_var):
    if call["exception_module"] == "builtins":
        return f"{builtins_alias}.{call['exception_type']}"
    if call["exception_module"] == "__main__":
        return f"{entry_module_var}.{call['exception_type']}"
    return f"{exception_aliases[call['exception_module']]}.{call['exception_type']}"


def main():
    argv = sys.argv[1:]
    if len(argv) not in (2, 3, 4):
        print(
            "usage: python -m ai_tracer.generator <trace_log> <target_dir> "
            "[output_dir] [entry_script]",
            file=sys.stderr,
        )
        sys.exit(1)
    trace_log_path, target_dir, *rest = argv
    output_dir = rest[0] if len(rest) > 0 else "generated_tests"
    entry_script = rest[1] if len(rest) > 1 else None
    for path in generate(trace_log_path, target_dir, output_dir, entry_script):
        print(path)


if __name__ == "__main__":
    main()
